### ISSUE TITLE
svg2png called multiple times

### ISSUE THREAD

**Issue by thewilkybarkid** [evilebottnawi/favicons#177]
Having an SVG source image causes svg2png to be used for each output, but it only needs to be called once. It's currently being used without concurrency limits too, leading to high memory usage.

**Comment by dangreen** [comment]
@thewilkybarkid svg2png is used for each output to provide a better quality of the resulting png images.

**Comment by brunocodutra** [comment]
>  leading to high memory usage.

I don't think rendering SVG was the culprit after all, because despite the fact `svg2png` is still executed for every icon generated generating all icons out of a SVG image takes roughly 5 seconds and loads about 120 MB of memory on my machine, while the figures for a similar looking PNG image are 16 seconds and 480 MB of memory.
